{{- $ports := dict -}}
{{- range .Values.app.service.ports -}}
  {{- $portName := .name | replace "-" "_" -}}
  {{- $_ := set $ports $portName .port -}}
{{- end -}}

{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: unifi-httproute-{{ $ports.dev_comm }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: unifi-gateway
    namespace: {{ .Release.Namespace }}
    sectionName: http-management
  hostnames:
  - {{ .Values.gateway.controller.host }}
  rules:
  - backendRefs:
    - name: unifi-controller-app
      port: {{ $ports.dev_comm }}
{{- end }}
