apiVersion: v1
kind: Service
metadata:
  name: unifi-db
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 27017
  selector:
    app: unifi-db

