apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-app
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    {{- range .Values.app.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app: unifi-controller-app

