apiVersion: v1
kind: Secret
metadata:
  name: unifi-mongo-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_USER: {{ .Values.db.env.MONGO_USER | b64enc | quote }}
  MONGO_PASS: {{ .Values.db.env.MONGO_PASS | b64enc | quote }}

